# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('field_type', models.CharField(choices=[('Grama natural', 'Grama natural'), ('Grama sintetica', 'Grama sintetica')], default=False, max_length=20, verbose_name='Tipo de material/grama de la cancha')),
                ('modality', models.CharField(max_length=40, verbose_name='Modalidad')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fields')),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_match_away_team', models.BooleanField(default=False)),
                ('match_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status_challenge', models.CharField(choices=[('Aceptado', 'Aceptado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('Fichaje', 'Fichaje')], default=True, max_length=40, verbose_name='Estado del desafío')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fields', verbose_name='Imagen de la plantilla o escudo')),
                ('modality', models.CharField(blank=True, choices=[('Fútbol 8', 'Fútbol 8'), ('Fútbol 6', 'Fútbol 6')], max_length=40, verbose_name='Modalidad')),
                ('branch', models.CharField(blank=True, choices=[('', ''), ('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=False, max_length=12, verbose_name='Rama')),
                ('category', models.CharField(blank=True, choices=[('', ''), ('Empresa', 'Empresa'), ('Barrio', 'Barrio'), ('Universidad', 'Universidad'), ('Colegio', 'Colegio'), ('Infantil', 'Infantil'), ('Master', 'Master'), ('Sin Categoría', 'Sin Categoría')], default='Sin Categoría', max_length=40, verbose_name='Categoría')),
                ('category_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('game_day', models.CharField(blank=True, max_length=150, verbose_name='Reservas o frecuencia de juego')),
                ('place_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games_information.Field', verbose_name='Lugar de origen')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games_information.Team', verbose_name='Equipo visitante'),
        ),
    ]
