# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('Grama natural', 'Grama natural'), ('Grama sintetica', 'Grama sintetica')], default=False, max_length=20, verbose_name='Tipo de material/grama de la cancha')),
                ('modality', multiselectfield.db.fields.MultiSelectField(choices=[('Fútbol 11', 'Fútbol 11'), ('Fútbol 8', 'Fútbol 8'), ('Fútbol 7', 'Fútbol 7'), ('Fútbol 6', 'Fútbol 6'), ('Fútbol 5', 'Fútbol 5')], max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='fields')),
                ('location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('image', models.ImageField(blank=True, upload_to='fields', verbose_name='Imagen de la plantilla o escudo')),
                ('modality', multiselectfield.db.fields.MultiSelectField(choices=[('Fútbol 11', 'Fútbol 11'), ('Fútbol 8', 'Fútbol 8'), ('Fútbol 7', 'Fútbol 7'), ('Fútbol 6', 'Fútbol 6'), ('Fútbol 5', 'Fútbol 5')], max_length=255)),
                ('place_origin', models.CharField(max_length=150, verbose_name='Lugar de origen')),
                ('game_day', models.CharField(max_length=150, verbose_name='Reservas o frecuencia de juego')),
                ('home_field', models.ManyToManyField(to='games_information.Field')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCompetitionCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(max_length=150)),
                ('fields', models.ManyToManyField(to='games_information.Field')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
