# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 21:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcompetitioncenter',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='place_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_information.Field', verbose_name='Lugar de origen'),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_information.Team', verbose_name='Equipo visitante'),
        ),
        migrations.AddField(
            model_name='match',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_information.Field', verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hometeam', to='games_information.Team', verbose_name='Equipo local'),
        ),
    ]
