# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-27 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_players_accept',
            field=models.ManyToManyField(blank=True, related_name='away_team_players_accept', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_players_cancel',
            field=models.ManyToManyField(blank=True, related_name='away_team_players_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='fichaje_players_match',
            field=models.ManyToManyField(blank=True, related_name='fichaje_players_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='field',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games_information.Field', verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hometeam', to='games_information.Team', verbose_name='Equipo local'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_players_accept',
            field=models.ManyToManyField(blank=True, related_name='home_team_players_accept', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_players_cancel',
            field=models.ManyToManyField(blank=True, related_name='home_team_players_cancel', to=settings.AUTH_USER_MODEL),
        ),
    ]
