# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
