# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games_information', '0004_auto_20161113_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_players_acept',
            field=models.ManyToManyField(blank=True, related_name='away_team_players_acept', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_players_cancel',
            field=models.ManyToManyField(blank=True, related_name='away_team_players_cancel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_players_acept',
            field=models.ManyToManyField(blank=True, related_name='home_team_players_acept', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_players_cancel',
            field=models.ManyToManyField(blank=True, related_name='home_team_players_cancel', to=settings.AUTH_USER_MODEL),
        ),
    ]
