# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0005_auto_20161117_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status_challenge',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('Fichaje', 'Fichaje')], default=True, max_length=40, verbose_name='Estado del desafío'),
        ),
    ]
