# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 16:40
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0005_auto_20160907_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='modality',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Fútbol 11', 'Fútbol 11'), ('Fútbol 8', 'Fútbol 8'), ('Fútbol 7', 'Fútbol 7'), ('Fútbol 6', 'Fútbol 6'), ('Fútbol 5', 'Fútbol 5')], max_length=255, null=True),
        ),
    ]
