# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 16:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games_information', '0006_auto_20161206_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='fichaje_players_match',
            field=models.ManyToManyField(blank=True, related_name='fichaje_players_match', to=settings.AUTH_USER_MODEL),
        ),
    ]
