# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0008_auto_20170103_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='branch',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=False, max_length=12, verbose_name='Rama'),
        ),
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('Empresa', 'Empresa'), ('Barrio', 'Barrio'), ('Universidad', 'Universidad'), ('Colegio', 'Colegio'), ('Infantil', 'Infantil'), ('Master', 'Master')], default=True, max_length=40, verbose_name='Categoría'),
        ),
    ]
