# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-15 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0008_auto_20170503_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='match',
            name='status_challenge',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado'), ('Fichaje', 'Fichaje')], max_length=40, verbose_name='Estado del desafío'),
        ),
    ]
