# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0008_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games_information.Field', verbose_name='Lugar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
