# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0010_auto_20170103_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='enterprise_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='team',
            name='school_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del colegio'),
        ),
        migrations.AlterField(
            model_name='team',
            name='town_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del barrio'),
        ),
        migrations.AlterField(
            model_name='team',
            name='university_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de la Universidad'),
        ),
    ]
