# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0010_match_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='name',
        ),
    ]
