# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0011_auto_20170103_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='enterprise_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='town_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='university_name',
        ),
        migrations.AddField(
            model_name='team',
            name='category_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='team',
            name='modality',
            field=models.CharField(choices=[('Fútbol 8', 'Fútbol 8'), ('Fútbol 6', 'Fútbol 6')], default=True, max_length=40, verbose_name='Modalidad'),
        ),
    ]
