# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0012_match_check_match_away_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='place_origin',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lugar de origen'),
        ),
    ]
