# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0013_auto_20170105_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('Empresa', 'Empresa'), ('Barrio', 'Barrio'), ('Universidad', 'Universidad'), ('Colegio', 'Colegio'), ('Infantil', 'Infantil'), ('Master', 'Master'), ('Sin Categoría', 'Sin Categoría')], default='Sin Categoría', max_length=40, verbose_name='Categoría'),
        ),
    ]
