# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0013_auto_20161029_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='place_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_information.Field', verbose_name='Lugar de origen'),
        ),
    ]
