# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-30 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0014_auto_20161029_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='modality',
            field=models.CharField(choices=[('Fútbol 11', 'Fútbol 11'), ('Fútbol 8', 'Fútbol 8'), ('Fútbol 7', 'Fútbol 7'), ('Fútbol 6', 'Fútbol 6'), ('Fútbol 5', 'Fútbol 5')], default=True, max_length=40, verbose_name='Modalidad'),
        ),
    ]
