# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-30 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0015_auto_20161030_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fields', verbose_name='Imagen de la plantilla o escudo'),
        ),
    ]
