# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0016_auto_20170112_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(blank=True, choices=[('Empresa', 'Empresa'), ('Barrio', 'Barrio'), ('Universidad', 'Universidad'), ('Colegio', 'Colegio'), ('Infantil', 'Infantil'), ('Master', 'Master'), ('Sin Categoría', 'Sin Categoría')], default='Sin Categoría', max_length=40, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='team',
            name='game_day',
            field=models.CharField(blank=True, max_length=150, verbose_name='Reservas o frecuencia de juego'),
        ),
        migrations.AlterField(
            model_name='team',
            name='modality',
            field=models.CharField(blank=True, choices=[('Fútbol 8', 'Fútbol 8'), ('Fútbol 6', 'Fútbol 6')], max_length=40, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='team',
            name='place_origin',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games_information.Field', verbose_name='Lugar de origen'),
        ),
    ]
