# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0017_auto_20170112_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='place_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games_information.Field', verbose_name='Lugar de origen'),
        ),
    ]
