# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0018_auto_20170112_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games_information.Team', verbose_name='Equipo visitante'),
        ),
        migrations.AlterField(
            model_name='match',
            name='field',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='games_information.Field', verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hometeam', to='games_information.Team', verbose_name='Equipo local'),
        ),
    ]
