# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0020_auto_20170203_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='id',
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
