# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-30 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0020_auto_20161030_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
