# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-09 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0021_auto_20161030_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='accept_challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='cancel_challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='pending_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
