# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.9 on 2016-11-09 19:26
=======
# Generated by Django 1.9.9 on 2016-11-10 17:01
>>>>>>> development
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0021_auto_20161030_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status_challenge',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default=True, max_length=40, verbose_name='Estado del desafío'),
        ),
    ]
