# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-11 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0022_match_status_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status_challenge',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], default=True, max_length=40, verbose_name='Estado del desafío'),
        ),
    ]
