# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import userprofiles.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games_information', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('sex', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=False, max_length=12, verbose_name='Sexo')),
                ('is_player', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=True, help_text='Designates whether the user can log into this admin site.')),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('nickname', models.CharField(blank=True, max_length=64)),
                ('number_matches', models.PositiveIntegerField(blank=True, null=True)),
                ('accomplished_matches', models.PositiveIntegerField(blank=True, null=True)),
                ('time_available', models.CharField(blank=True, max_length=255)),
                ('leg_profile', models.CharField(blank=True, max_length=64)),
                ('number_shirt_preferred', models.CharField(blank=True, max_length=255)),
                ('team_support', models.CharField(blank=True, max_length=255)),
                ('player_preferred', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games_information.Team', verbose_name='Equipo en el que juega')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', userprofiles.managers.UserManager()),
            ],
        ),
    ]
