# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0001_initial'),
        ('userprofiles', '0002_user_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ManyToManyField(null=True, to='games_information.Team', verbose_name='Equipo en el que juega'),
        ),
    ]
