# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0003_auto_20160822_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ManyToManyField(to='games_information.Team', verbose_name='Equipo en el que juega'),
        ),
    ]
