# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0004_auto_20160822_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ManyToManyField(null=True, to='games_information.Team', verbose_name='Equipos en los que juega'),
        ),
    ]
