# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0019_auto_20170127_2212'),
        ('userprofiles', '0004_auto_20170127_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='players', to='games_information.Team', verbose_name='Equipo en el que juega'),
        ),
    ]
