# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0001_initial'),
        ('userprofiles', '0005_auto_20160822_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='team',
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games_information.Team', verbose_name='Equipo en el que juega'),
        ),
    ]
