# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0005_auto_20170131_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games_information.Team', verbose_name='Equipo en el que juega'),
        ),
    ]
