# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import userprofiles.managers


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0006_auto_20160822_1707'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', userprofiles.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
