# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_information', '0006_auto_20160907_1640'),
        ('userprofiles', '0008_remove_user_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games_information.Team', verbose_name='Equipo en el que juega'),
        ),
    ]
