# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0010_auto_20161017_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accomplished_matches',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_matches',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
