# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0012_auto_20161026_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
