# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-29 23:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0015_auto_20161029_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
    ]
