# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-31 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0024_auto_20161030_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=12, verbose_name='Sexo'),
        ),
    ]
