# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-31 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0025_auto_20161031_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('', 'All'), (1, 'Masculino'), (2, 'Femenino')], max_length=12, verbose_name='Sexo'),
        ),
    ]
