# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-01 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0026_auto_20161031_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('Portero', 'Portero'), ('Defensa Central', 'Defensa Central'), ('Defensa Lateral Derecho', 'Defensa Lateral Derecho'), ('Defensa Lateral Izquierdo', 'Defensa Lateral Izquierdo'), ('Media Punta (por el centro adelantado)', 'Media Punta (por el centro adelantado)'), ('Medio Centro (en el centro)', 'Medio Centro (en el centro)'), ('Medio Campo Defensivo', 'Medio Campo Defensivo'), ('Medio Izquierda', 'Medio Izquierda'), ('Medio Derecha', 'Medio Derecha'), ('Delantero Centro (siempre pendientes de meter goles)', 'Delantero Centro (siempre pendientes de meter goles)'), ('Extremo Derecho (los más adelantados por la banda)', 'Extremo Derecho (los más adelantados por la banda)'), ('Extremo Izquierdo', 'Extremo Izquierdo'), ('Segundo Delantero', 'Segundo Delantero')], default=True, max_length=334, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=False, max_length=12, verbose_name='Sexo'),
        ),
    ]
