# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-10 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0027_auto_20161101_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=255),
        ),
    ]
